language: python
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "pip install virtualenv"
  - "./metrique.py firstboot metrique"
  - "./metrique.py deploy --slow --all"
services: 
  - mongodb
addons:
    postgresql: "9.3"
script: 
  - "coverage run --source=metrique -m py.test tests"
before_script:
  - psql -c 'create database admin;' -U postgres
after_success:
  - coveralls
after_failure:
  - "cat ~/.metrique/*"
