language: python
python:
  - "2.7"
install:
  - "sudo apt-get install pigz"
  - "pip install coveralls virtualenv"
  - "pip install decorator"
  - "pip install anyconfig"  # temporary fix, easy_install anyconfig not working
  - "./metrique.py deploy --all"
  - "./metrique.py firstboot metrique postgresql"
addons:
    postgresql: "9.3"
script: 
  - "coverage run --source=metrique -m py.test tests"
after_success:
  - coveralls
