language: python
python:
  - "2.6"
  - "2.7"
# install metrique and dependencies to a virtenv
install:
  - "sudo apt-get install libhdf5-serial-dev"
  - "./manage.py deploy --matplotlib --slow"
services: 
  - mongodb
# NOTE: authentication will be enabled upon adding an 
# admin user as mongod is started with the --auth parameter.
#before_script:
# -
script: 
# run tests
  - "py.test tests"
