language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install ./src/metriqueu --use-mirrors"
  - "pip install ./src/metrique --use-mirrors"
  - "pip install ./src/metriqued --use-mirrors"
  - "pip install ./src/metriquec --use-mirrors"
services: 
  - mongodb
before_script:
  - "mkdir ~/.metrique"
  - "./src/metriqued/bin/metriqued start -d 2 -f"
# command to run tests
script: 
  - "python -m pytest src/metriqueu"
  - "python -m pytest src/metrique"
  - "python -m pytest src/metriquec"
  - "python -m pytest src/metriqued"
