language: python
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "./metrique deploy --slow --develop"
services: 
  - mongodb
script: 
  - "coverage run --source=metrique,metriqued,metriqueu,metriquec -m py.test tests"
after_success:
  - coveralls
after_failure:
  - "cat ~/.metrique/*"
