language: python
python:
  - "2.6"
  - "2.7"
# install metrique and dependencies to a virtenv
install:
  - "pip install coveralls"
  - "sudo apt-get install libhdf5-serial-dev"
  - "./manage.py deploy --matplotlib --slow"
services: 
  - mongodb
# NOTE: authentication will be enabled upon adding an 
# admin user as mongod is started with the --auth parameter.
#before_script:
# -
script: 
  # run tests
  #- "py.test tests"
  # test coverage badge
  - "coverage run --source=metrique,metriqued,metriqueu,metriquec py.test tests"
# test coverage badge
after_success:
  coveralls
