language: python
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "pip install virtualenv"
  - "./metrique.py firstboot"
  - "./metrique.py deploy --slow --all"
services: 
  - mongodb
script: 
  - "coverage run --source=metrique -m py.test tests"
after_success:
  - coveralls
after_failure:
  - "cat ~/.metrique/*"
